=== DerimB/assignment-1--databases--cs-365--fall-2023/xml/dtd/student.dtd
<!ELEMENT university (student)+>
<!ELEMENT student (personal-information, university-information)>
<!ELEMENT personal-information (first-name,middle-name,last-name,preferred-name,student-ID,email,phone)>
<!ELEMENT first-name (#PCDATA)>
<!ELEMENT middle-name (#PCDATA)>
<!ELEMENT last-name (#PCDATA)>
<!ELEMENT preferred-name (#PCDATA)>
<!ELEMENT student-ID (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT university-information (year-status,GPA,major,minor,enrollment-status,advisor,date-of-initial-enrollment,graduation-date)>
<!ELEMENT year-status (#PCDATA)>
<!ELEMENT GPA (#PCDATA)>
<!ELEMENT major (#PCDATA)>
<!ELEMENT minor (#PCDATA)>
<!ELEMENT enrollment-status (#PCDATA)>
<!ELEMENT advisor (#PCDATA)>
<!ELEMENT date-of-initial-enrollment (#PCDATA)>
<!ELEMENT graduation-date (#PCDATA)>

=== DerimB/assignment-1--databases--cs-365--fall-2023/xml/index.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/css" href="..\xml\css\style.css"?>
<!DOCTYPE university SYSTEM "..\xml\dtd\student.dtd"[
]>
<university>
    <student>
        <personal-information> 
            <first-name>Gordon</first-name>
            <middle-name>Matthew</middle-name>
            <last-name>Sumner</last-name>
            <preferred-name>Sting</preferred-name>
            <student-ID>1234567</student-ID>
            <email>sting@thepolice.com</email>
            <phone>212.123.4567</phone>
        </personal-information>
        <university-information>
            <year-status>first year</year-status>
            <GPA>4.0</GPA>
            <major>Music</major>
            <minor>English</minor>
            <enrollment-status>full-time</enrollment-status>
            <advisor>Andy Summers</advisor>
            <date-of-initial-enrollment>08-25-1969</date-of-initial-enrollment>
            <graduation-date>05-01-1973</graduation-date>
        </university-information>
    </student>
    <student>
        <personal-information> 
            <first-name>Kim</first-name>
            <middle-name>N/A</middle-name>
            <last-name>Thayil</last-name>
            <preferred-name>N/A</preferred-name>
            <student-ID>4567890</student-ID>
            <email>kim@soundgarden.com</email>
            <phone>206.123.4567</phone>
        </personal-information>
        <university-information>
            <year-status>second year</year-status>
            <GPA>3.0</GPA>
            <major>Philosophy</major>
            <minor>Music</minor>
            <enrollment-status>full-time</enrollment-status>
            <advisor>Chris Cornell</advisor>
            <date-of-initial-enrollment>08-25-1978</date-of-initial-enrollment>
            <graduation-date>05-01-1982</graduation-date>
        </university-information>
    </student>
</university>
